# Configuration for WPDistillery executed by setup.sh
#
# Author: Flurin Dürst
# URL: https://wpdistillery.org
#
# For detailed instructions on this file read the config.yml-documentation at
# https://wpdistillery.org/documentation/config-yml-documentation/
#
# File Version: 1.6.4


# INSTALLATION
#################################################################

# WordPress folder
wpfolder: public

# WordPress version
wpversion: latest

# language/timezone
wplocale: en_ZA
timezone: "Africa/Johannesburg"

# admin user settings
admin:
  user: "digitalleap"
  password: admin
  email: admin@digitalleap.co.za
  first_name: ""
  last_name: ""

# scotch box db access
db:
  name: scotchbox
  user: root
  pass: root
  prefix: wp_

# SETTINGS
#################################################################

wpsettings:
  url: localhost.dev
  title: Example Title
  description: Example Description
  permalink_structure: "/%postname%/"
  thumbnail_width: 150
  thumbnail_height: 150
  medium_width: 300
  medium_height: 300
  large_width: 1024
  large_height: 1024
  # use page as frontpage
  page_on_front: true
    frontpage_name: Example Front Page
  # automatic conversion of smilies
  convert_smilies: false

# THEME
#################################################################

# theme to install, choose new name in 'rename' or leave empty
theme:
  name: LayersWP
  rename: ""
  url: "https://www.dropbox.com/s/27yg4dm83ii85sj/layerswp.zip?dl=1"

# PLUGINS
#################################################################

# plugins to install & activate
plugins_active:
  - "https://www.dropbox.com/s/mmqj1xb9shpmtpf/layers-updater-1-3.zip?dl=1"
  - "https://www.dropbox.com/s/hod0whavnhymnzq/layers-pro.zip?dl=1"

# plugins to install
plugins_inactive:
  #ecommerce
  - woocommerce
  #administration
  - wordpress-seo
  - "https://www.dropbox.com/s/gight5f5ij5eyxt/gravityforms.zip?dl=1"
  - redirection
  #security/backup
  - wp-security-audit-log

# WPDISTILLERY SETUP
####################################################################
# if you don't want the setup to run all tasks, set them to false

setup:
  wp: true
  settings: true
  theme: true
  plugins: true
  cleanup: true
    comment: true
    posts: true
    files: true
    themes: true
